obj-$(CONFIG_DRM_PANEL_FAIRPHONE_FP2_OTM1902B) += panel-fairphone-fp2-otm1902b.o
obj-$(CONFIG_DRM_PANEL_FAIRPHONE_FP2_S6D6FA1) += panel-fairphone-fp2-s6d6fa1.o
obj-$(CONFIG_DRM_PANEL_SONY_LEO_NOVATEK_LGD) += panel-sony-leo-novatek-lgd.o
obj-$(CONFIG_DRM_PANEL_SONY_ARIES_TOSHIBA_720P_VIDEO) += panel-sony-aries-toshiba-720p-video.o
obj-$(CONFIG_DRM_PANEL_SONY_ARIES_NOVATEK_DEFAULT_0) += panel-sony-aries-novatek-default-0.o
obj-$(CONFIG_DRM_PANEL_SONY_ARIES_NOVATEK_DEFAULT_1) += panel-sony-aries-novatek-default-1.o
obj-$(CONFIG_DRM_PANEL_SONY_ARIES_NOVATEK_JDI) += panel-sony-aries-novatek-jdi.o
obj-$(CONFIG_DRM_PANEL_SONY_ARIES_NOVATEK_SHARP) += panel-sony-aries-novatek-sharp.o
